### ISSUE TITLE
Can't compile with latest fips

### ISSUE THREAD

**Issue by mgerhardy** [fungos/fips-assimp#2]
FIPS_RTTI must be set to true

/home/mgerhardy/dev/fips-assimp/assimp/code/FBXDocument.h:249:2:   required from here
/home/mgerhardy/dev/fips-assimp/assimp/code/FBXProperties.h:78:37: error: ‘dynamic_cast’ not permitted with -fno-rtti
/home/mgerhardy/dev/fips-assimp/assimp/code/FBXProperties.h: In instantiation of ‘const T\* Assimp::FBX::Property::As() const [with T = Assimp::FBX::TypedProperty<int>]’:
/home/mgerhardy/dev/fips-assimp/assimp/code/FBXProperties.h:154:69:   required from ‘T Assimp::FBX::PropertyGet(const Assimp::FBX::PropertyTable&, const string&, const T&) [with T = int; std::string = std::basic_string<char>]’

**Comment by fungos** [comment]
Do you know how to set it in a way that will work when being imported?
Anyway, I've forced it in the target, there is some warning about some C files, but it is working here.
